const silentPatient =`The Silent Patient is a shocking psychological thriller of a woman’s act of violence against her husband—and of the therapist obsessed with uncovering her motive
Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London’s most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.
Alicia’s refusal to talk, or give any kind of explanation, turns a domestic tragedy into something far grander, a mystery that captures the public imagination and casts Alicia into notoriety. The price of her art skyrockets, and she, the silent patient, is hidden away from the tabloids and spotlight at the Grove, a secure forensic unit in North London.`

const percyJackson = `Plot. Set in the mid-2000s, the series follows the story of Perseus "Percy" Jackson, a boy who discovers he is a demigod son of Poseidon. He was abandoned by his father because of an oath made by the Big Three (Zeus, Poseidon and Hades), the sons of Kronos, to not father any more children after World War II. Percy's journey turns even more electrifying when he discovers that numerous people and ancient monsters are trying to kill him due to his status as a demigod, latent strength, and growing influence in the Greek world. Percy also finds out that there are even more demigods like him in Camp Half-Blood, a training camp in Long Island.

With his friend Annabeth Chase, and his best friend and companion Grover Underwood (a satyr who Percy finds out is actually his protector), his journey across the frightening mystic worlds begins. Percy soon finds himself fulfilling extraordinary quests, prophecies, and fighting battles with and for the gods against the rising threat of the Titans.[9] He also finds himself at a crossroads: either he helps in the destruction of the world, or in preserving it.`

const americanPsycho=`Patrick Bateman is a wealthy investment banker in his 20’s in the late 1980’s. We follow him as he and his friends live a life of vanity, drugs, and a lot of violence. And we get to see first hand of the world Patrick lives in get his unfiltered thoughts in a stream-of-consciousness narrative. That leads to one of the darkest characters and protagonist who in my opinion is far scarier than even Hannibal Lecter.

During the day, Patrick and his friends bash each other and everyone who comes across their vision. At night, Patrick gives in to his darker thoughts and decides to kill. But that doesn’t satisfy his thoughts and he is plunged towards a nightmarish run that leaves many hurt and dead.`

const nameOfTheWind = `The Kingkiller Chronicle takes place in the fictional world of Temerant, a large continent of which the known part, called the Four Corners of Civilization, is divided into several distinct nations and cultures. Much of the world follows a faith vaguely similar to medieval Christianity. Coexisting alongside the mortal world is the realm of the Fae, a parallel universe inhabited by supernatural creatures which can move between the two realms only when the moon is full. Magic exists in Temerant, too, but obeys a well-defined set of rules and principles that can only be exploited by those who have trained in its professional and scientific use.

As the novel begins, the reader hears an old storyteller speaking of a famous old wizard called Taborlin the Great, who was captured by evil beings called the Chandrian. Escaping them, Taborlin fell from a great height—but since he knew the "Name of the Wind", he called it and the Wind came and set him down safely. In later parts of the book, characters are often skeptical of such stories. Some kinds of magic are taught in the university as academic disciplines and have daily-life applications (those who can afford it are able to buy magical lamps, for example, much better than the candles used by poorer people). However, most of the population does not have reliable knowledge of the magical disciplines and many still doubt that magicians can truly call upon the Wind. The Chandrian—whose appearance is supposedly heralded by flames turning blue—are often dismissed as mythical bogeymen.`

const harryPotter = `arry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry. The main story arc concerns Harry's struggle against Lord Voldemort, a dark wizard who intends to become immortal, overthrow the wizard governing body known as the Ministry of Magic and subjugate all wizards and Muggles (non-magical people).

The series was originally published in English by Bloomsbury in the United Kingdom and Scholastic Press in the United States. All versions around the world are printed by Grafica Veneta in Italy.[1] A series of many genres, including fantasy, drama, coming-of-age fiction, and the British school story (which includes elements of mystery, thriller, adventure, horror, and romance), the world of Harry Potter explores numerous themes and includes many cultural meanings and references.[2] According to Rowling, the main theme is death.[3] Other major themes in the series include prejudice, corruption, and madness.[4]`

const you=`Joe Goldberg works in a bookstore in New York City. One day, a young woman named Beck enters the store. She immediately attracts Joe’s attention. After their short interaction, he develops an obsession with Beck. He learns her name and researches everything he can about Beck on the Internet. She is an aspiring writer at college in New York. Joe follows Beck to a bar and lingers nearby, listening to her friends. He lurks outside her apartment and watches her through her open curtains. When her boyfriend, Benji, visits her apartment, Joe develops an intense dislike for him. Joe breaks into Beck’s apartment and is nearly caught, exiting quickly through a window when she returns home. 

Beck reads one of her short stories at an event in a bar. Joe follows her to the bar and watches her with her friends. They drink heavily, and, later that night, he stands near her on a subway platform. Beck slips onto the tracks, and Joe helps her back on to the platform. They share a taxi back to Beck’s apartment, where she thanks him for saving her life. They are greeted by an unimpressed, arrogant Benji. Joe steals Beck’s phone, though she assumes it is lost.`

const theVinciCode = `The Da Vinci Code is a 2003 mystery thriller novel by Dan Brown. It is Brown's second novel to include the character Robert Langdon: the first was his 2000 novel Angels & Demons. The Da Vinci Code follows symbologist Robert Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris causes them to become involved in a battle between the Priory of Sion and Opus Dei over the possibility of Jesus Christ and Mary Magdalene having had a child together.

The novel explores an alternative religious history, whose central plot point is that the Merovingian kings of France were descended from the bloodline of Jesus Christ and Mary Magdalene, ideas derived from Clive Prince's The Templar Revelation (1997) and books by Margaret Starbird. The book also refers to The Holy Blood and the Holy Grail (1982) though Dan Brown has stated that it was not used as research material.`

const theWitcher= `Geralt of Rivia, a brooding professional monster hunter for hire also known as witcher, struggles to keep his humanity in a medieval dark fantasy world ruled by corrupt kings, queens and mages, where poverty, violence and intolerance are rampant, normal humans are sometimes worse than actual monsters and most jobs that pay well involve the darkest of human emotions and desires. Yennefer of Vengerberg is an ambitious mage who came from nothing and wants everything. Princess Cirilla or Ciri is a young girl who may or may not possess some great mysterious power within her. Their destinies, seemingly quite different, slowly intertwine in a rather cosmic fashion. Their companions include Jaskier the bard, Geralt's endearingly annoying friend and hype man vowed to spread the word of his heroics throughout the continent even if he has to embellish them a little for a few coins more, Tissaia de Vries, Yennefer's secretive mentor who believes in tough love, and Triss Merigold, a good-natured druidic mage and trustworthy friend. The Nilfgaardian Empire's sudden brutal invasion of the kingdom of Cintra ruled by Cirilla's protective grandmother, warrior queen Calanthe, puts their lives in great danger.

Geralt of Rivia is a witcher, a mutant with special powers who kills monsters for money. The land is in a state of turmoil, due to the empire of Nilfgaard seeking to enlarge its territory. Among the refugees of this struggle is Cirilla, the Princess of Cintra, one of Nilfgaard's victims. She and Geralt share a destiny. Meanwhile, another figure looms large in Geralt's adventures: Yennefer, a sorceress.`

export {
    silentPatient,
    you,
    theVinciCode,
    theWitcher,
    harryPotter,
    nameOfTheWind,
    americanPsycho,
    percyJackson
}